

#lista de tokens para a análise
tokens = [
    ["comment", r"\/\/*.*"],
    ["newline", r"\n"],
    ["main", r"\bmain\b"],
    ["char", r"\bchar\b"],
    ["int", r"\bint\b"],
    ["long", r"\blong\b"],
    ["float", r"\bfloat\b"],
    ["const", r"\bconst\b"],
    ["double", r"\bdouble\b"],
    ["if", r"\bif\b"],
    ["else", r"\belse\b"],
    ["while", r"\bwhile\b"],
    ["for", r"\bfor\b"],
    ["struct", r"\bstruct\b"],
    ["signed", r"\bsigned\b"],
    ["unsigned", r"\bunsigned\b"],
    ["return", r"\breturn\b"],
    ["do", r"\bdo\b"],
    ["break", r"\bbreak\b"],
    ["static", r"\bstatic\b"],
    ["void", r"\bvoid\b"],
    ["sizeof", r"\bsizeof\b"],
    ["pointer_operator", r"\b\*"],
    ["dereference_operator", r"\b\*"],
    ["lesser_than", r"\b<\b"],
    ["greater_than", r"\b>\b"],
    ["lesser_or_equal_to", r"\b<=\b"],
    ["greater_or_equal_to", r"\b>=\b"],
    ["equal_to", r"\b==\b"],
    ["unequal_to", r"\b!=\b"],
    ["declare", r'\b\=\b'],
    ["or", r"\|\|"],
    ["open_parenthesis", r"\("],
    ["close_parenthesis", r"\)"],
    ["open_brackets", r"\{"],
    ["close_brackets", r"\}"],    
    ["and", r'&&'],
    ["int_value", r"\b[-+]?\d+\b"],
    ["float_value", r"\b[+-]?\d[.]\d?\b"],
    ["comma", r","],
    ["semicolon", r";"],
    ["plus", r"\+"],
    ["minus", r"-"],
    ["multiply", r"\*"],
    ["divide", r'\/'],
    ["quotes", r"'"],
    ["double_quotes", r'"'],
    ["identifier", r'\b[A-Za-z][A-Za-z0-9_]{1,30}\b'],
]

